### ISSUE TITLE
Empty space accumulation at the end of masonary

### ISSUE THREAD

**Issue by idavidgeo** [sibiraj-s/react-layout-masonry#3]
Using react18 with nextjs13.5, importing without SSR like so: `const Masonry = dynamic(() => import('react-layout-masonry'), { ssr: false });`

Images are not placed correctly, resulting in accumulation of empty space as more images are loaded.

Issue still persists if all images are loaded at once (not added dynamically as seen in the clip)

See clip here: https://streamable.com/72rnz1

**Comment by sibiraj-s** [comment]
Thanks for opening this issue. 

Can you share a reproducible version using [stackblitz](https://stackblitz.com/)? And can you double check if there aren't any other styles affecting the layout? Meanwhile I'll check whats happening there.

**Comment by sibiraj-s** [comment]
I think I understand the problem. ReactLayoutMasonry does not know the size of the image that is going to be rendered. It just tries to fit the contents in the masonry layout. What you see might be probably because of the size of the image returned from the endpoint is either wider or smaller than expected and too many of them might have ended on the first few columns, hence it appears as misaligned.

**Comment by idavidgeo** [comment]
I'm pretty sure that's the case as well. Looks like this is more of a limitation rather than a bug. I just tested the same photos on a different package and got the same result.

**Comment by idavidgeo** [comment]
It would be pretty awesome to perhaps pass the width/height or just the aspect ratio of the image to then determine where to add the next image. I'll try to explore this.

Nonetheless, great lightweight project!

**Comment by sibiraj-s** [comment]
Thank you. Yes its a limitation. I'll keep an eye on it and see if it can be improved somehow.
