### ISSUE TITLE
Adding support for SSR

### ISSUE THREAD

**Issue by cooltaiwanesesam** [sibiraj-s/react-layout-masonry#6]
This is a great lightweight package. But it's currently limited to client side only. Will you consider adding support for SSR. For example adding a `defaultColumns` prop when there is a User-Agent header, then client side hydration once the window sizes are available.

**Comment by sibiraj-s** [comment]
SSR would be a great addition, but internally using hooks to dynamically calculate window size and breakpoints is coupled together. A slight refactor might be needed there.

> adding a defaultColumns prop when there is a User-Agent header

Also, I am not sure how a standalone package will be able to do that.

Currently I am occupied with several things. It would take time to work on this TBH. But, I am happy to discuss more on this. Feel free to throw in the ideas to make it happen. If there is a better solution, We can make it happen.

**Comment by cooltaiwanesesam** [comment]
All I did was simply change the `DEFAULT_COLUMNS` to reference the context value which was set by the User-Agent header. This works for me.

`
const useColumnsCount = (columns) => {
  const isMobile = useRecoilValue(isMobileState);
  const isDesktop = useRecoilValue(isDesktopState);
  const DEFAULT_COLUMNS = isMobile ? 2 : isDesktop ? 4 : 3;

  ...

  return columnsCount;
};
`
For the library, you can pass the value from the prop and let the user handle the default columns with your pre-defined fall back value.

**Comment by cooltaiwanesesam** [comment]
To support SSR, in the `useWindowWidth` hook, you can set the width after mounted to remove SSR error.

```javascript
const useWindowWidth = (isResponsive: boolean = true): number => {
  const [windowWidth, setWindowSize] = useState(null);

  useEffect(() => {
    setWindowSize(window.innerWidth)
  },[])
  ...
  return windowWidth;
};
``` 
To avoid Cumulative Layout Shift (CLS), you can change `const DEFAULT_COLUMNS = 3;` into optional props with a default value of 3, this allows users to handle the `defaulColumns` depends on how they get the User-Agent header. Example:
```javascript
    <Masonry
      columns={{ 640: 1, 768: 2, 1024: 3, 1280: 5 }}
      defaultColumns={isMobile ? 1 :  isDesktop ? 3 :  2}
      gap={16}
    >
      {items.map((item) => {
        return <Item {...item} />;
      })}
    </Masonry>
```

**Comment by sibiraj-s** [comment]
For frameworks like Next.js and astro, the fact that useEffect is present without `use client` being added will throw errors, regardless of how its used. 🤔

**Comment by sibiraj-s** [comment]
Added `use-client` directive in Masonry component so it renders in Server Components without errors by default.

**Comment by mucluck** [comment]
Doesn't work in Next.js 15, `use client` directive disappears

**Comment by sibiraj-s** [comment]
Hi, I am not sure that's an issue with this package. As you can see the source https://github.com/sibiraj-s/react-layout-masonry/blob/master/src/Masonry.tsx, the `use client` directive is added, why its removed is upto the toolchain you have to decide, it could be nextjs itself or something else.

If you think this is an issue here, kindly provide enough info to debug further.

Even though the use-client directive is added to this library, this is just to add some level of convenience. I wouldn't recommend adding it in the library, since its an application concern and not a library one. Few things might not work on all cases. There are some scenarios like explained over here https://github.com/adobe/react-spectrum/pull/5826#issue-2121756169 could also happen. Having the directive here might cause some issues in future when new things are added, but currently works so its left as is.
